CREATE DATABASE citasbd;

USE citasbd;

CREATE TABLE Cita (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombreCompleto VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    fechaHora DATETIME NOT NULL,
    categoria VARCHAR(255) NOT NULL,
    servicio VARCHAR(255) NOT NULL
);

CREATE TABLE Hombres (
  id INT AUTO_INCREMENT PRIMARY KEY,
  DirecImgServicio VARCHAR(255) NOT NULL,
  NombreServicio VARCHAR(255) NOT NULL,
  CostoServicio DECIMAL(10, 2) NOT NULL,
  DescripcionServicio TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE Cita ADD COLUMN createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Cita ADD COLUMN updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

select * from Hombres